# Generated by Django 4.2.7 on 2025-01-23 21:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('cargo_desejado', models.CharField(max_length=100)),
                ('escolaridade', models.CharField(max_length=50)),
                ('observacoes', models.CharField(blank=True, max_length=300, null=True)),
                ('arquivo', models.FileField(upload_to='curriculos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('ip', models.GenericIPAddressField()),
                ('data_hora_envio', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
