# Generated by Django 4.2.7 on 2025-01-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='ip',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
