# Generated by Django 4.2.7 on 2025-01-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_alter_candidato_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='data_hora_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
